# Generated by Django 4.2.14 on 2024-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidReportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
