# Generated by Django 4.2.14 on 2024-07-30 06:58

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidReportsApp', '0002_userregistration_last_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userregistration',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
