# Generated by Django 4.2.14 on 2024-08-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidReportsApp', '0005_alter_userregistration_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userregistration',
            managers=[
            ],
        ),
    ]
