# Generated by Django 4.2.14 on 2024-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidReportsApp', '0006_alter_userregistration_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
